config/routes.rb
Rails.application.routes.draw do
  root "post#index"
  namespace :admin do
    resources :posts
  end
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  layout "admin/layouts/application"
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @admin_posts = Post.all
  end

  # GET /admin/posts/1
  # GET /admin/posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @admin_post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @admin_post = Post.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to @admin_post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @admin_post }
      else
        format.html { render :new }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @admin_post.update(admin_post_params)
        format.html { redirect_to @admin_post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_post }
      else
        format.html { render :edit }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_post_params
      params.fetch(:admin_post, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all
  end

  def show
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/layouts/_header.html.slim
/! Navbar
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  /! Left navbar links
  ul.navbar-nav
    li.nav-item
      a.nav-link data-widget="pushmenu" href="#" role="button" 
        i.fas.fa-bars
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link href="index3.html"  Home
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link href="#"  Contact
    li.nav-item.dropdown
      a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
        | Help
      .dropdown-menu aria-labelledby="navbarDropdown" 
        a.dropdown-item href="#"  FAQ
        a.dropdown-item href="#"  Support
        .dropdown-divider
        a.dropdown-item href="#"  Contact
  /! SEARCH FORM
  form.form-inline.ml-3
    .input-group.input-group-sm
      input.form-control.form-control-navbar aria-label="Search" placeholder="Search" type="search" /
      .input-group-append
        button.btn.btn-navbar type="submit" 
          i.fas.fa-search

app/views/admin/layouts/_sidebar.html.slim
/! Main Sidebar Container
aside.main-sidebar.sidebar-dark-primary.elevation-4
  /! Brand Logo
  a.brand-link href="index3.html" 
    = image_tag(asset_pack_path('media/img/AdminLTELogo.png'), :class => "brand-image img-circle elevation-3")
    span.brand-text.font-weight-light AdminLTE 3
  /! Sidebar
  .sidebar
    /! Sidebar user panel (optional)
    
    .user-panel.mt-3.pb-3.mb-3.d-flex
      .image
        = image_tag(asset_pack_path('media/img/user1-128x128.jpg'), :class => "img-circle elevation-2 ")
      .info
        a.d-block href="#"  Alexander Pierce
    /! Sidebar Menu
    nav.mt-2
      ul.nav.nav-pills.nav-sidebar.flex-column data-widget="treeview" role="menu" 
        /!
          | Add icons to the links using the .nav-icon class
          | with font-awesome or any other icon font library
        li.nav-item
          a.nav-link href="#" 
            i.nav-icon.fab.fa-spotify
            p 
              | Airlines
        li.nav-item
          a.nav-link href="#" 
            i.nav-icon.fas.fa-th
            p
              | Simple Link
              span.right.badge.badge-danger New
    /! /.sidebar-menu
  /! /.sidebar

app/views/admin/layouts/application.html.slim
doctype html
html
  head
    title RailsSlimBlogTutorial
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_pack_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body.hold-transition.sidebar-mini.layout-fixed
    .wrapper
      = render 'admin/layouts/header'
      = render 'admin/layouts/sidebar'
      .content-wrapper
        .content-header
          .container-fluid
            = yield 

app/views/admin/posts/_form.html.slim
= form_for @admin_post do |f|
  - if @admin_post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_post.errors.count, "error")} prohibited this admin_post from being saved:"
      ul
        - @admin_post.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/admin/posts/edit.html.slim
h1 Editing admin_post

== render 'form'

=> link_to 'Show', @admin_post
'|
=< link_to 'Back', admin_posts_path

app/views/admin/posts/index.html.slim
h1 Listing admin_posts

table
  thead
    tr
      th
      th
      th

  tbody
    - @admin_posts.each do |admin_post|
      tr
        td = link_to 'Show', admin_post
        td = link_to 'Edit', edit_admin_post_path(admin_post)
        td = link_to 'Destroy', admin_post, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Post', new_admin_post_path

app/views/admin/posts/new.html.slim
h1 New admin_post

== render 'form'

= link_to 'Back', admin_posts_path

app/views/admin/posts/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_admin_post_path(@admin_post)
'|
=< link_to 'Back', admin_posts_path

app/views/layouts/_header.html.slim
/! Navbar
nav.main-header.navbar.navbar-expand.navbar-light.navbar-white
  .container
    a.navbar-brand href="index3.html" 
      = image_tag(asset_pack_path('media/img/AdminLTELogo.png'), :class => "brand-image img-circle elevation-3")
      span.brand-text.font-weight-light AdminLTE 3
    /! Left navbar links
    ul.navbar-nav
      li.nav-item
      li.nav-item.d-none.d-sm-inline-block
        a.nav-link href="index3.html"  Home
      li.nav-item.d-none.d-sm-inline-block
        a.nav-link href="#"  Contact
      li.nav-item.dropdown
        a#navbarDropdown4.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
          | Help
        .dropdown-menu aria-labelledby="navbarDropdown4" 
          a.dropdown-item href="#"  FAQ
          a.dropdown-item href="#"  Support
          .dropdown-divider
          a.dropdown-item href="#"  Contact
    /! SEARCH FORM
    form.form-inline.ml-3
      .input-group.input-group-sm
        input.form-control.form-control-navbar aria-label="Search" placeholder="Search" type="search" /
        .input-group-append
          button.btn.btn-navbar type="submit" 
            i.fas.fa-search
    /! Right navbar links
    ul.navbar-nav.ml-auto
      /! Messages Dropdown Menu
      li.nav-item.dropdown
        a.nav-link data-toggle="dropdown" href="#" 
          i.fas.fa-comments
          span.badge.badge-danger.navbar-badge 3
        .dropdown-menu.dropdown-menu-lg.dropdown-menu-right
          a.dropdown-item href="#" 
            /! Message Start
          .media
            img.img-size-50.mr-3.img-circle alt=("User Avatar") src="dist/img/user1-128x128.jpg" /
            .media-body
              h3.dropdown-item-title
                | Brad Diesel
                span.float-right.text-sm.text-danger
                  i.fas.fa-star
              p.text-sm Call me whenever you can...
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
          /! Message End
          .dropdown-divider
          a.dropdown-item href="#" 
            /! Message Start
          .media
            img.img-size-50.img-circle.mr-3 alt=("User Avatar") src="dist/img/user8-128x128.jpg" /
            .media-body
              h3.dropdown-item-title
                | John Pierce
                span.float-right.text-sm.text-muted
                  i.fas.fa-star
              p.text-sm I got your message bro
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
          /! Message End
          .dropdown-divider
          a.dropdown-item href="#" 
            /! Message Start
          .media
            img.img-size-50.img-circle.mr-3 alt=("User Avatar") src="dist/img/user3-128x128.jpg" /
            .media-body
              h3.dropdown-item-title
                | Nora Silvester
                span.float-right.text-sm.text-warning
                  i.fas.fa-star
              p.text-sm The subject goes here
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
          /! Message End
          .dropdown-divider
          a.dropdown-item.dropdown-footer href="#"  See All Messages
      /! Notifications Dropdown Menu
      li.nav-item.dropdown
        a.nav-link data-toggle="dropdown" href="#" 
          i.far.fa-bell
          span.badge.badge-warning.navbar-badge 15
        .dropdown-menu.dropdown-menu-lg.dropdown-menu-right
          span.dropdown-header 15 Notifications
          .dropdown-divider
          a.dropdown-item href="#" 
            i.fas.fa-envelope.mr-2
            | 4 new messages
            span.float-right.text-muted.text-sm 3 mins
          .dropdown-divider
          a.dropdown-item href="#" 
            i.fas.fa-users.mr-2
            | 8 friend requests
            span.float-right.text-muted.text-sm 12 hours
          .dropdown-divider
          a.dropdown-item href="#" 
            i.fas.fa-file.mr-2
            | 3 new reports
            span.float-right.text-muted.text-sm 2 days
          .dropdown-divider
          a.dropdown-item.dropdown-footer href="#"  See All Notifications
      li.nav-item
        a.nav-link data-slide="true" data-widget="control-sidebar" href="#" role="button" 
          i.fas.fa-th-large
/! /.navbar

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsSlimBlogTutorial
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_pack_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body.hold-transition.sidebar-mini.layout-fixed
    .wrapper
      = render 'layouts/header'
      = render 'layouts/sidebar'
      .content-wrapper
        .content-header
          .container-fluid
            = yield 

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th
      th
      th

  tbody
    - @posts.each do |post|
    
      tr
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

br
.btn.btn-primary.mr-5 thienhoa
.btn.btn-danger thienhoa

= link_to 'New Post', new_post_path

app/views/posts/show.html.slim
h1 
  = @post.title
p
  = @post.content